Ch intergrate travisci 164046240
andela/ah-legion-backend pull request #3
Opened 2019-02-27 08:14 UTC by Etomovich

**What does this PR do?**
This PR configures Travis CI and adds coverage and build badge to the README.md

**Description of task to be completed?**
- configure Travis CI
- configure Coveralls
- add coverage and build badges to README.md

**How should	this be manually tested?**
- none

**Any background context you may want to provide?**
- none

**What are the relevant pivotal tracer stories?**
- #164046240
- #164046243

2019-02-27 08:19 UTC, ElMonstro commented
Add background context to PR message

2019-02-27 08:52 UTC, abulojoshua1 commented on .coveralls.yml
> +repo_token: bZWUyvMiRymHxVnOIP20PUAC2lt6vx7iZ
@Etomovich, add an end of file here.

2019-02-27 08:52 UTC, abulojoshua1 commented on .travis.yml
> +  - coveralls
@Etomovich, add an end of file here.

2019-02-27 08:52 UTC, abulojoshua1 commented on .travis.yml
> +  	- python manage.py test
Use the same indentation on all lines in this file.

2019-02-27 08:53 UTC, abulojoshua1 commented
@Etomovich, you are having another person's commits in this PR, please rebase well and remove those commits from your file.

2019-02-27 09:08 UTC, abulojoshua1 commented on .travis.yml
> +  - "2.7"
@Etomovich, narrow the tests to python 3.7 only.

2019-02-27 10:46 UTC, Etomovich commented
@abulojoshua1 I have seen my error I raised a PR to master rather than develop sorry for the oversight.

2019-02-27 15:22 UTC, ElMonstro requested changes
Please fix this Error in travis build "Unable to download 3.7 archive. The archive may not exist. Please consider a different version.
". Consider changing the python version t0  3.6.

2019-02-27 19:04 UTC, MandelaK commented
@Etomovich could you squash your commits into one? Also please try and make sure the build is passing, it could be a problem with your travis.yml configuration, but I am not so sure

2019-02-28 04:30 UTC, cob04 reviewed
Would you please squash your three commits into one.

2019-02-28 04:44 UTC, Etomovich commented
> @Etomovich could you squash your commits into one? Also please try and make sure the build is passing, it could be a problem with your travis.yml configuration, but I am not so sure

Keith no test have been configured yet in this branch. I will expect the tests to be added before Travis can pass.

2019-02-28 05:07 UTC, Etomovich commented
> Would you please squash your three commits into one.

I have squashed the changes, any more feedback will be highly appreciated.

2019-02-28 05:08 UTC, Etomovich commented
> Please fix this Error in travis build "Unable to download 3.7 archive. The archive may not exist. Please consider a different version.
> ". Consider changing the python version t0 3.6.

I have downgraded it to python version 3.6. As per you recommendations. Thanks.

2019-02-28 05:22 UTC, ElMonstro approved these changes

2019-02-28 06:33 UTC, BrianSerem reviewed
Please input the link to Travis CI  as a way of testing instead of 'none'

2019-02-28 06:45 UTC, Etomovich commented
> Please input the link to Travis CI as a way of testing instead of 'none'

Will do!!

2019-02-28 07:26 UTC, merged