chore(tests): write unit tests for implemented functionality
andela/ah-legion-backend pull request #4
Opened 2019-02-27 13:51 UTC by MandelaK

### What does this PR do?
- write unit tests for models
- write unit tests for views
- write unit tests for serializers
- install coverage to get coverage and create .coveragerc file to configure ignored files

### Description of the task to be completed
The codebase currently includes implemented functionality for the project. We wrote tests that assert that all currently implemented functionality works without changing any of the code. We also wrote integration tests for the views. 

### How can this be manually tested?
- Clone this repository using `git clone https://github.com/andela/ah-legion-backend.git`
- Checkout to this branch using `git checkout ch-initial-unit-tests-164046234`
- Make sure to install coverage, it is included in the requirements.txt file.
- Make sure you have your environment variables configured in a .env file 
- Run tests using `coverage run manage.py test --settings=authors.settings.test`
- To get coverage, you can run the command `coverage report`

### Any background context you want to provide?
We only wrote tests for currently implemented features and did not alter any functionality.

### What are the relevant PT stories?
[#164046234](https://www.pivotaltracker.com/story/show/164046234)

2019-02-27 13:59 UTC, cob04 submitted a review, later dismissed
tests run, coverage is at 97%

2019-02-27 15:04 UTC, Etomovich submitted a review, later dismissed
The test seem to be running well good to see.

2019-02-28 04:21 UTC, ElMonstro submitted a review, later dismissed
Good test coverage

2019-02-28 04:57 UTC, BrianSerem submitted a review, later dismissed
Looks good, good job with the tests

2019-02-28 07:00 UTC, RachelleMaina reviewed
python-decouple is not in the requirements.txt. I also get this error `ValueError: Dependency on app with no migrations: authentication`

2019-02-28 08:13 UTC, abulojoshua1 commented on .coveragerc
> +show_missing = True
@MandelaK, please add an End of File here.

2019-02-28 08:13 UTC, abulojoshua1 commented on authors/settings/base.py
> +}
Please add End of File here.

2019-02-28 08:13 UTC, abulojoshua1 commented on authors/apps/authentication/tests/test_views.py
> +        self.assertEqual(response.status_code, status.HTTP_200_OK)
Please add End of File here.

2019-02-28 08:25 UTC, BrianSerem approved these changes
Looks fine

2019-02-28 08:27 UTC, abulojoshua1 approved these changes
LGTM

2019-02-28 08:28 UTC, Etomovich approved these changes
Nice job, Keith your build is working nice job!!

2019-02-28 08:28 UTC, abulojoshua1 requested changes

2019-02-28 08:28 UTC, abulojoshua1 commented on authors/apps/authentication/tests/test_models.py
> +        self.assertEqual(self.user1.get_short_name(), "user")
@MandelaK, please add EOF here.

2019-02-28 08:32 UTC, MandelaK commented on authors/apps/authentication/tests/test_models.py
> +        self.assertEqual(self.user1.get_short_name(), "user")
Ok, done

2019-02-28 08:32 UTC, cob04 approved these changes
Travis in the green

2019-02-28 08:36 UTC, abulojoshua1 approved these changes
LGTM

2019-02-28 08:37 UTC, merged